### ISSUE TITLE
Three-way comparisons?

### ISSUE THREAD

**Issue by krassowski** [jorvlan/open-visualizations#4]
For some time now I was thinking about best practices when extending a pair-plot to multi-way comparisons. Right now I am working on doing a three-way comparisons using the idea of a hive plot.

Here is a hive plot from [ggraph's introduction](https://www.data-imaginist.com/2017/ggraph-introduction-layouts/) for context:
![image](https://user-images.githubusercontent.com/5832902/81342487-3ae33e80-90ab-11ea-8134-010257140a4b.png)

Do you have any other suggestions or ideas? Would you like me to contribute here if I suceed with anything on this front?

**Comment by jorvlan** [comment]
Hi, that looks impressive, but I must say that I am not familiar with such plots, yet. Therefore, my first intuition is that I find it difficult to quickly understand what such a plot tells me. While a pair-plot does a quicker job at telling me the results, obviously since it is a less complex comparison. But yea, I think if you can come up with something, just let me know.
